### ISSUE TITLE
Add `osmnx-base`

### ISSUE THREAD

**Issue by cheginit** [conda-forge/osmnx-feedstock#116]
Similar to the feedstock of [GeoPandas](https://github.com/conda-forge/geopandas-feedstock/blob/main/recipe/meta.yaml), I recommend adding a `osmnx-base` output containing the hard dependencies only. This could be useful for package maintainers who only use specific parts of `osmnx` and might not require the optional dependencies of `osmnx`. This will not impact other users who install `osmnx` from Conda.

**Comment by gboeing** [comment]
@cheginit this seems reasonable. @ocefpaf are there any issues or anything to keep in mind with offering a `package-base` output?

**Comment by ocefpaf** [comment]
> [@cheginit](https://github.com/cheginit) this seems reasonable. [@ocefpaf](https://github.com/ocefpaf) are there any issues or anything to keep in mind with offering a `package-base` output?

No issues. Just be sure to use `${PYTHON} -m pip install . -vv --no-deps --no-build-isolation` when building it with multiple outputs. There is a bug that pulls packages from pip if those flags are not used. BTW, I believe geopandas is not using that! We can be safe b/c pip won't worried what is in the env already, but we should fix that in geopandas regardless.

**Comment by gboeing** [comment]
@cheginit would you like to open a PR accordingly?

**Comment by cheginit** [comment]
@gboeing Sure, would be happy to.

**Comment by gboeing** [comment]
Closed by #117
