### ISSUE TITLE
Unable to import OSXnx

### ISSUE THREAD

**Issue by pagonsri** [conda-forge/osmnx-feedstock#33]
ImportError                               Traceback (most recent call last)
<ipython-input-12-4a0d15e28291> in <module>()
----> 1 import osmnx as ox
      2 ox.plot_graph(ox.graph_from_place('Modena, Italy'))

~\Anaconda3\lib\site-packages\osmnx\__init__.py in <module>()
      7 ################################################################################
      8 
----> 9 from .buildings import *
     10 from .elevation import *
     11 from .core import *

~\Anaconda3\lib\site-packages\osmnx\buildings.py in <module>()
      7 
      8 import time
----> 9 import geopandas as gpd
     10 import matplotlib.pyplot as plt
     11 from matplotlib.collections import PatchCollection

~\Anaconda3\lib\site-packages\geopandas\__init__.py in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

~\Anaconda3\lib\site-packages\geopandas\io\file.py in <module>()
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 import six

~\Anaconda3\lib\site-packages\fiona\__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

~\Anaconda3\lib\site-packages\fiona\collection.py in <module>()
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: DLL load failed: The specified module could not be found.

**Comment by pagonsri** [comment]
I've installed OSMnx on conda-forge already

**Comment by gboeing** [comment]
This is an error in conda-forge GDAL installation (a dependency of OSMnx), rather than an error in OSMnx installation itself. See: https://github.com/conda-forge/gdal-feedstock/issues/219 and especially this: https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-411230004

**Comment by ocefpaf** [comment]
You are on Windows and I'm pretty sure that, if you do a `conda-list` on your envs you'll see that some of your packages are coming from `defaults` and not `conda-forge`. This is probably related to https://github.com/conda/conda/issues/7626

Closing b/c it is not actionable at the moment. We need to wait for a bugfix in `conda` :unamused:
