### ISSUE TITLE
best way to install from conda-forge

### ISSUE THREAD

**Issue by gboeing** [conda-forge/osmnx-feedstock#34]
In light of https://github.com/conda-forge/fiona-feedstock/issues/89#issuecomment-413238946 I want to make sure OSMnx is set up properly and that users are provided the correct installation instructions.

  1. Do I need to change anything in its feedstock recipe to ensure it installs dependencies exclusively from conda-forge and not defaults?
  2. What are the best installation instructions for users to install it from conda-forge without mixing channels?

I had provided these instructions in the past to try to make a pure conda-forge environment, but it is now unsolvable and I'm unsure why:

```
>>>conda create --override-channels -c conda-forge -n OSMNX python=3 osmnx

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - osmnx
  - geopandas[version='>=0.2.1']
  - gdal=2.1
  - osmnx
  - geopandas[version='>=0.2.1']
  - pysal
  - scipy[version='>=0.11']

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by ocefpaf** [comment]
Ah! You found our kryptonite! Conda-forge does not have scipy on Windows yet and my suggestion is moot there :-(

@isuruf I what is the status of https://github.com/conda-forge/scipy-feedstock/pull/78 ?

**Comment by gboeing** [comment]
Just checking back on this best practice question, as it seems there have been some changes over the past month.

**Comment by ocefpaf** [comment]
If you can afford to use a single channel, and for `osmnx` that means `conda-forge` b/c it is not available on `defaults`, that is always safer. However, things are stabilizing and using multiple channels "should" be OK now.

Note that only after the compiler migration, which is still happening, that using both channels side-by-side will be 100% OK.
