### ISSUE TITLE
Drive networks between two city are not connected 

### ISSUE THREAD

**Issue by Hartry** [conda-forge/osmnx-feedstock#47]
Hii everyone,

I ' am getting a drive network of a city in France ( Aubervilliers, France ) with the following code
`
add_Aubervilliers = "Aubervilliers, France"
Graphe_Aubervilliers = ox.graph_from_place(add_Aubervilliers, network_type='drive')
`
on which I can applying an Dijkstra algorithm.

But when I trying to apply the same algorithm with a composed graph two connected city (both Saint Denis and Aubervilliers in France)  It doesn't works nicely ... I mean, starting from some node, the algorithm doesn't find a way. :-/

`
add_Saint_denis = " Saint denis, France "
Graphe_Saint_denis = ox.graph_from_place(add_Saint_denis, network_type = "drive")
Graph_Paris_Auber = nx.compose_all([ Graphe_Saint_denis, Graphe_Aubervilliers ])
`
It's the same when I compose the graph of paris, Aubervilliers or saint Denis ...

I noticed that some road (intersection) connecting aubervilliers and saint Denis weren't identified. 
None road is connected to Aubervilliers or saint denis ....

Did I missed something ?

**Comment by ocefpaf** [comment]
Looks like a usage question that is better asked on StackOverflow or mailing lists. This is just the repository that packages `osmnx`. I can't help you there.

**Comment by Hartry** [comment]
Oh okay, i m sorry

**Comment by ocefpaf** [comment]
> Oh okay, i m sorry

No problem. I blame google for putting this so high up in the search results :smile:
