### ISSUE TITLE
Error importing osmnx installed with conda

### ISSUE THREAD

**Issue by adrianelizalde** [conda-forge/osmnx-feedstock#58]
Issue:
I installed OSMnx through conda:
```
conda config --prepend channels conda-forge
conda create -n ox --strict-channel-priority osmnx 
```
No able to import osmnx
```
import osmnx os
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d4a103aeed40> in <module>
----> 1 import osmnx as ox

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/osmnx/__init__.py in <module>
      7 ################################################################################
      8 
----> 9 from .core import *
     10 from .downloader import *
     11 from .elevation import *

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/osmnx/core.py in <module>
      7 ################################################################################
      8 
----> 9 import geopandas as gpd
     10 import logging as lg
     11 import math

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/geopandas/__init__.py in <module>
      3 from geopandas.array import _points_from_xy as points_from_xy  # noqa
      4 
----> 5 from geopandas.io.file import read_file  # noqa
      6 from geopandas.io.sql import read_postgis  # noqa
      7 from geopandas.tools import sjoin  # noqa

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/geopandas/io/file.py in <module>
      4 import pandas as pd
      5 
----> 6 import fiona
      7 from shapely.geometry import mapping
      8 from shapely.geometry.base import BaseGeometry

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/fiona/__init__.py in <module>
     82     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     83 
---> 84 from fiona.collection import BytesCollection, Collection
     85 from fiona.drvsupport import supported_drivers
     86 from fiona.env import ensure_env_with_credentials, Env

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: dlopen(/opt/anaconda3/envs/ox/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Library not loaded: @rpath/libnetcdf.15.dylib
  Referenced from: /opt/anaconda3/envs/ox/lib/libgdal.26.dylib
  Reason: image not found

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  2019.10                  py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.3                      py_0
appnope                   0.1.0                    py37_0
appscript                 1.1.0            py37h1de35cc_0
asn1crypto                1.0.1                    py37_0
astroid                   2.3.1                    py37_0
astropy                   3.2.2            py37h1de35cc_0
atomicwrites              1.3.0                    py37_1
attrs                     19.2.0                     py_0
babel                     2.7.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.5                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.8.0                    py37_0
bitarray                  1.0.1            py37h1de35cc_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               hd9629dc_0
bokeh                     1.3.4                    py37_0
boost-cpp                 1.70.0               hd59e818_1    conda-forge
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h1d22016_1
bzip2                     1.0.8                h1de35cc_0
ca-certificates           2019.8.28                     0
cachetools                4.0.0                    pypi_0    pypi
cairo                     1.14.12           h9d4d9ac_1005    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37hb5b8e2f_0
chardet                   3.0.4                 py37_1003
click                     6.7                      pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.5.0                    pypi_0    pypi
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
conda                     4.8.3            py37hc8dfbb8_0    conda-forge
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h1de35cc_0
conda-verify              3.4.2                      py_1
contextlib2               0.6.0                      py_0
cryptography              2.7              py37ha12b0ac_0
cssselect                 1.1.0                    pypi_0    pypi
curl                      7.65.3               ha441bb4_0
cycler                    0.10.0                   py37_0
cython                    0.29.13          py37h0a44026_0
cytoolz                   0.10.0           py37h1de35cc_0
dask                      2.5.2                      py_0
dask-core                 2.5.2                      py_0
dbus                      1.13.6               h90a0687_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
distributed               2.5.2                      py_0
docutils                  0.15.2                   py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
expat                     2.2.6                h0a44026_0
fastcache                 1.1.0            py37h1de35cc_0
filelock                  3.0.12                     py_0
fiona                     1.8.13.post1             pypi_0    pypi
flask                     1.1.1                      py_0
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.9.1                hb4e5f40_0
freexl                    1.0.5             h1de35cc_1002    conda-forge
fsspec                    0.5.2                      py_0
future                    0.17.1                   py37_0
gdal                      2.3.3            py37hbe65578_0
geoalchemy2               0.6.3                    pypi_0    pypi
geomancer                 1.1.0                    pypi_0    pypi
geopandas                 0.7.0                    pypi_0    pypi
geos                      3.7.1             h0a44026_1000    conda-forge
get_terminal_size         1.0.0                h7520d66_0
gettext                   0.19.8.1             h15daf44_3
gevent                    1.4.0            py37h1de35cc_0
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.56.2               hd9629dc_0
glob2                     0.7                        py_0
gmp                       6.1.2                hb37e062_1
gmpy2                     2.0.8            py37h6ef4df4_2
google-api-core           1.16.0                   pypi_0    pypi
google-auth               1.11.3                   pypi_0    pypi
google-cloud-bigquery     1.9.0                    pypi_0    pypi
google-cloud-core         0.29.1                   pypi_0    pypi
google-resumable-media    0.5.0                    pypi_0    pypi
googleapis-common-protos  1.51.0                   pypi_0    pypi
greenlet                  0.4.15           py37h1de35cc_0
h5py                      2.9.0            py37h3134771_0
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.4               hfa1e0ec_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
icu                       58.2                 h4b95b61_1
idna                      2.7                      pypi_0    pypi
imageio                   2.6.0                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.23                     py37_0
intel-openmp              2019.4                      233
ipykernel                 5.1.2            py37h39e3cac_0
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              0.24                     pypi_0    pypi
jbig                      2.1                  h4d881f8_0
jdcal                     1.4.1                      py_0
jedi                      0.15.1                   py37_0
jinja2                    2.10.3                     py_0
joblib                    0.13.2                   py37_0
jpeg                      9b                   he5867d9_2
json-c                    0.13.1            h1de35cc_1001    conda-forge
json5                     0.8.5                      py_0
jsonschema                3.0.2                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.3                    py37_1
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
kealib                    1.4.7                hf5ed860_6
keyring                   18.0.0                   py37_0
kiwisolver                1.1.0            py37h0a44026_0
krb5                      1.16.1               hddcf347_7
lazy-object-proxy         1.4.2            py37h1de35cc_0
libarchive                3.3.3                h786848e_5
libcurl                   7.65.3               h051b688_0
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
libgdal                   2.3.3                h0950a36_0
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                 hdd342a3_7
libkml                    1.3.0             hed7d534_1010    conda-forge
liblief                   0.9.0                h2a1bed3_2
libnetcdf                 4.6.1                hd5207e6_2
libpng                    1.6.37               ha441bb4_0
libpq                     11.2                 h051b688_0
libsodium                 1.0.16               h3efe00b_0
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                ha12b0ac_0
libtiff                   4.0.10               hcb84e12_2
libxml2                   2.9.9                hf6e021a_1
libxslt                   1.1.33               h33a18ac_0
llvm-openmp               4.0.1                hcfea43d_1
llvmlite                  0.29.0           py37h98b8051_0
locket                    0.2.0                    py37_1
loguru                    0.4.1                    pypi_0    pypi
lxml                      4.4.1            py37hef8c89e_0
lz4-c                     1.8.1.2              h1de35cc_0
lzo                       2.10                 h362108e_2
markupsafe                0.23                     pypi_0    pypi
matplotlib                3.1.1            py37h54f8f79_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37h1de35cc_0
mkl                       2019.4                      233
mkl-service               2.3.0            py37hfbe908c_0
mkl_fft                   1.0.14           py37h5e564d8_0
mkl_random                1.1.0            py37ha771720_0
mock                      3.0.5                    py37_0
more-itertools            7.2.0                    py37_0
mpc                       1.1.0                h6ef4df4_1
mpfr                      4.0.1                h3018a27_3
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h04f5b5a_1
multipledispatch          0.6.0                    py37_0
munch                     2.5.0                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.0                    py37_1
nbformat                  4.4.0                    py37_0
ncurses                   6.1                  h0a44026_1
networkx                  2.3                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.1                    py37_0
numba                     0.45.1           py37h6440ff4_0
numexpr                   2.7.0            py37h7413580_0
numpy                     1.17.2           py37h99e6662_0
numpy-base                1.17.2           py37h6575580_0
numpydoc                  0.9.1                      py_0
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0
openjpeg                  2.3.1                hdc36067_1    conda-forge
openpyxl                  3.0.0                      py_0
openssl                   1.1.1d               h1de35cc_2
packaging                 19.2                       py_0
pandas                    0.25.1           py37h0a44026_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parsel                    1.5.2                    pypi_0    pypi
parso                     0.5.1                      py_0
partd                     1.0.0                      py_0
path.py                   12.0.1                     py_0
pathlib2                  2.3.5                    py37_0
patsy                     0.5.1                    py37_0
pcre                      8.43                 h0a44026_0
pep8                      1.7.1                    py37_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.0            py37hb68e598_0
pip                       19.2.3                   py37_0
pixman                    0.34.0            h1de35cc_1003    conda-forge
pkginfo                   1.5.0.1                  py37_0
plaid-python              3.4.0                    pypi_0    pypi
pluggy                    0.13.0                   py37_0
ply                       3.11                     py37_0
poppler                   0.65.0               ha097c24_1
poppler-data              0.4.9                         1    conda-forge
proj4                     5.2.0             h6de7cb9_1006    conda-forge
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.10                     py_0
protobuf                  3.11.3                   pypi_0    pypi
psutil                    5.6.3            py37h1de35cc_0
ptyprocess                0.6.0                    py37_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37h1413db1_2
pyarrow                   0.12.1                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybigquery                0.4.14                   pypi_0    pypi
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37h1de35cc_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37h1de35cc_9
pycurl                    7.43.0.3         py37ha12b0ac_0
pyflakes                  2.1.1                    py37_0
pygments                  2.4.2                      py_0
pylint                    2.4.2                    py37_0
pyodbc                    4.0.27           py37h0a44026_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.2                      py_0
pyproj                    2.6.0                    pypi_0    pypi
pyqt                      5.9.2            py37h655552a_2
pyrsistent                0.15.4           py37h1de35cc_0
pysocks                   1.7.1                    py37_0
pytables                  3.5.2            py37h5bccee9_1
pytest                    5.2.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.4.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.4                h359304d_1
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                     py37_13
python-linkedin-v2        0.9.4                    pypi_0    pypi
python.app                2                        py37_9
python3-linkedin          1.0.2                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0
pywavelets                1.0.3            py37h1d22016_1
pyyaml                    5.1.2            py37h1de35cc_0
pyzmq                     18.1.0           py37h0a44026_0
qt                        5.9.7                h468cd18_1
qtawesome                 0.6.0                      py_0
qtconsole                 4.5.5                      py_0
qtpy                      1.9.0                      py_0
readline                  7.0                  h1de35cc_5
requests                  2.20.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
ripgrep                   0.10.0               hc07d326_0
rope                      0.14.0                     py_0
rsa                       4.0                      pypi_0    pypi
ruamel_yaml               0.15.46          py37h1de35cc_0
scikit-image              0.15.0           py37h0a44026_0
scikit-learn              0.21.3           py37h27c97d8_0
scipy                     1.3.1            py37h1410ff5_0
seaborn                   0.9.0                    py37_0
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                    py37_0
setuptools                41.4.0                   py37_0
shapely                   1.7.0                    pypi_0    pypi
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h0a44026_0
six                       1.12.0                   py37_0
snappy                    1.1.7                he62c110_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.3                    py37_0
sphinx                    2.2.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.2                    py37_0
sqlalchemy                1.3.2                    pypi_0    pypi
sqlite                    3.30.0               ha441bb4_0
statsmodels               0.10.1           py37h1d22016_0
sympy                     1.4                      py37_0
tbb                       2019.8               h04f5b5a_0
tblib                     1.4.0                      py_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                ha441bb4_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37h1de35cc_0
tqdm                      4.36.1                     py_0
traitlets                 4.3.3                    py37_0
unicodecsv                0.14.1                   py37_0
unixodbc                  2.3.7                h1de35cc_0
urllib3                   1.24.2                   py37_0
w3lib                     1.21.0                   pypi_0    pypi
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
wrapt                     1.11.2           py37h1de35cc_0
wurlitzer                 1.0.3                    py37_0
xerces-c                  3.2.2             h4db8090_1003    conda-forge
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.1                      py_0
xlwings                   0.15.10                  py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h1de35cc_4
yaml                      0.1.7                hc338f04_2
zeromq                    4.3.1                h0a44026_3
zict                      1.0.0                      py_0
zipp                      0.6.0                      py_0
zlib                      1.2.11               h1de35cc_3
zstd                      1.3.7                h5bba6e5_0
</details>

<details>

```
$ conda info

```
     active environment : base
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /Users/tatiananinpeco/.condarc
 populated config files : /Users/tatiananinpeco/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __osx=10.12.6
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/tatiananinpeco/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/tatiananinpeco/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.20.0 CPython/3.7.4 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : /Users/tatiananinpeco/.netrc
           offline mode : False
</details>

**Comment by ocefpaf** [comment]
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/39 should fix this.

**Comment by ocefpaf** [comment]
Should be solved now.
