### ISSUE TITLE
cannot import name 'CRS' from 'pyproj' (C:\Users\veron\anaconda3\lib\site-packages\pyproj\__init__.py)

### ISSUE THREAD

**Issue by Veronika760** [conda-forge/osmnx-feedstock#85]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: cannot import name 'CRS' from 'pyproj' (C:\Users\veron\anaconda3\lib\site-packages\pyproj\__init__.py)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by gboeing** [comment]
Is this regarding an OSMnx installation? It doesn't look like you installed it in a virtual environment. Did you follow the documented [installation](https://osmnx.readthedocs.io/en/stable/#installation) instructions?

**Comment by ocefpaf** [comment]
@Veronika760 Can you send us the results of `conda list` and `conda info` for that environment? Without that information it is hard to figure out what is happening.
